"""Generate workshop/contracts/models.py (pydantic v2) from contracts/*.schema.json.

Usage: python contracts/scripts/gen_python.py [--check] [--out PATH]

The 16 schemas are bundled into one schema with local references only, `if`/`then`/`else`
are dropped (the models are typing helpers; jsonschema enforces the conditionals), and
datamodel-code-generator turns the bundle into pydantic models.
"""

from __future__ import annotations

import argparse
import copy
import json
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from workshop.contracts import CONTRACT_VERSION, TYPE_FILES  # noqa: E402
from workshop.contracts.validate import load_schema  # noqa: E402

DEFAULT_OUT = REPO_ROOT / "workshop" / "contracts" / "models.py"
HEADER = (
    f"# GENERATED by contracts/scripts/gen_python.py from contracts/*.schema.json "
    f"(contract v{CONTRACT_VERSION}). Do not edit.\n"
)
SCHEMA_URI = "https://json-schema.org/draft/2020-12/schema"
FILE_TITLES = {file_name: type_name for type_name, file_name in TYPE_FILES.items()}
DROPPED_KEYS = ("if", "then", "else")
FLAGS = [
    "--input-file-type", "jsonschema",
    "--output-model-type", "pydantic_v2.BaseModel",
    "--target-python-version", "3.11",
    "--use-standard-collections",
    "--use-union-operator",
    "--enum-field-as-literal", "all",
    "--use-schema-description",
    "--use-field-description",
    "--field-constraints",
    "--use-double-quotes",
    "--disable-timestamp",
    "--use-title-as-name",
    "--extra-fields", "forbid",
    "--use-one-literal-as-default",
    "--formatters", "builtin",
]  # fmt: skip


def rewrite_refs(node: object, title: str) -> None:
    """Point every `$ref` at the bundle's `#/$defs/<Title><Key>` names."""
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            node["$ref"] = rewrite_ref(ref, title)
        for value in node.values():
            rewrite_refs(value, title)
    elif isinstance(node, list):
        for value in node:
            rewrite_refs(value, title)


def rewrite_ref(ref: str, title: str) -> str:
    if ref.startswith("#/$defs/"):
        return f"#/$defs/{title}{ref.removeprefix('#/$defs/')}"
    file_name, _, fragment = ref.partition("#")
    target = FILE_TITLES[file_name]
    if not fragment:
        return f"#/$defs/{target}"
    if fragment.startswith("/$defs/"):
        return f"#/$defs/{target}{fragment.removeprefix('/$defs/')}"
    raise ValueError(f"unsupported $ref: {ref}")


def drop_conditionals(node: object) -> None:
    if isinstance(node, dict):
        for key in DROPPED_KEYS:
            node.pop(key, None)
        for value in node.values():
            drop_conditionals(value)
    elif isinstance(node, list):
        for value in node:
            drop_conditionals(value)


def build_bundle() -> dict:
    bundle: dict = {"$schema": SCHEMA_URI, "title": "VeilContracts", "$defs": {}}
    for type_name in TYPE_FILES:
        schema = copy.deepcopy(load_schema(type_name))
        schema.pop("$schema", None)
        schema.pop("$id", None)
        title = schema["title"]
        nested = schema.pop("$defs", {})
        rewrite_refs(schema, title)
        for key, value in nested.items():
            rewrite_refs(value, title)
            bundle["$defs"][title + key] = value
        bundle["$defs"][title] = schema
    drop_conditionals(bundle)
    return bundle


def generate() -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        bundle = build_bundle()
        (tmp_dir / "bundle.json").write_text(json.dumps(bundle, indent=2), encoding="utf-8")
        command = [
            sys.executable, "-m", "datamodel_code_generator",
            "--input", str(tmp_dir / "bundle.json"),
            "--output", str(tmp_dir / "models.py"),
            *FLAGS,
        ]  # fmt: skip
        subprocess.run(command, check=True)
        body = (tmp_dir / "models.py").read_bytes().decode("utf-8").replace("\r\n", "\n")
    return (HEADER + body).encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file on disk is stale")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output file")
    args = parser.parse_args(argv)

    content = generate()
    if args.check:
        if not args.out.exists() or args.out.read_bytes() != content:
            print(
                f"STALE: {args.out} differs from the schemas; run contracts/scripts/gen_python.py"
            )
            return 1
        print(f"UP TO DATE: {args.out}")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(content)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
