# GENERATED by contracts/scripts/gen_python.py from contracts/*.schema.json (contract v1.0). Do not edit.
# generated by datamodel-codegen:
#   filename:  bundle.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class VeilContracts(RootModel[Any]):
    root: Any = Field(..., title="VeilContracts")


class Rect(BaseModel):
    """
    An axis-aligned rectangle on the screen. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] | None = None
    """
    Contract version this object follows.
    """
    x: int = Field(..., ge=-100000, le=100000)
    """
    Left edge (top-left corner x). Negative values are allowed for items scrolled partly or fully off-screen.
    """
    y: int = Field(..., ge=-100000, le=100000)
    """
    Top edge (top-left corner y). Negative values are allowed for items scrolled partly or fully off-screen.
    """
    w: int = Field(..., ge=1, le=100000)
    """
    Width in screen pixels.
    """
    h: int = Field(..., ge=1, le=100000)
    """
    Height in screen pixels.
    """


class Frame(BaseModel):
    """
    Metadata of one captured screen frame; pixels are never part of a contract. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    frameId: int = Field(..., ge=0)
    """
    Increases with every delivered frame within a capture session.
    """
    sessionId: str | None = Field(None, pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Capture session this frame belongs to.
    """
    tMs: int = Field(..., ge=0)
    """
    Capture time.
    """
    width: int = Field(..., ge=1, le=8192)
    """
    Frame width in pixels at capture scale (e.g. 360).
    """
    height: int = Field(..., ge=1, le=8192)
    """
    Frame height in pixels at capture scale (e.g. 792).
    """
    screenWidth: int = Field(..., ge=1, le=16384)
    """
    Full-resolution screen width in the current orientation. Conversion: x_frame = x_screen * width / screenWidth.
    """
    screenHeight: int = Field(..., ge=1, le=16384)
    """
    Full-resolution screen height in the current orientation.
    """
    rotation: Literal[0, 90, 180, 270]
    """
    Display rotation in degrees.
    """
    source: Literal["mediaProjection", "accessibilityScreenshot", "replay", "screenshotFile"]
    """
    Where the frame came from.
    """
    foregroundPackage: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app in the foreground.
    """
    ownOverlay: list[Rect] = Field(..., max_length=64)
    """
    Veil's own covers visible at capture time, in screen pixels (may be empty).
    """
    blindRects: list[Rect] | None = Field(None, max_length=16)
    """
    Areas known to be black or protected from capture.
    """
    image: str | None = Field(None, max_length=260, min_length=1)
    """
    File name when the frame is stored on disk.
    """


class UiEventScrolled(BaseModel):
    """
    The content of a scrollable container moved.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["scrolled"] = "scrolled"
    """
    Event kind.
    """
    packageName: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app that produced the event.
    """
    dx: int
    """
    How far the content moved horizontally on screen, in screen pixels: +dx means it moved right. Opposite sign to Android's scroll delta.
    """
    dy: int
    """
    How far the content moved vertically on screen, in screen pixels: +dy means it moved down, -dy means it moved up (the user scrolled towards later content). Opposite sign to Android's scroll delta.
    """
    containerRect: Rect | None = None
    """
    Bounds of the scrolled container.
    """
    containerId: str | None = Field(None, max_length=128)
    """
    Identifier of the scrolled container.
    """
    estimated: bool | None = None
    """
    True when the scroll was derived from frame differences.
    """


class UiEventWindowChanged(BaseModel):
    """
    The foreground window changed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["windowChanged"] = "windowChanged"
    """
    Event kind.
    """
    packageName: str = Field(..., pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$")
    """
    Package name of the app that produced the event.
    """
    className: str | None = Field(None, max_length=200)
    """
    Class name of the new window.
    """
    windowId: int | None = None
    """
    Android window id.
    """


class ChangeType(RootModel[str]):
    root: str = Field(..., max_length=32)


class UiEventContentChanged(BaseModel):
    """
    Content inside a window changed without a scroll.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["contentChanged"] = "contentChanged"
    """
    Event kind.
    """
    packageName: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app that produced the event.
    """
    rect: Rect | None = None
    """
    Area that changed.
    """
    changeTypes: list[ChangeType] | None = Field(None, max_length=8)
    """
    Android content change type names.
    """


class UiEventScreenOff(BaseModel):
    """
    The screen turned off.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["screenOff"] = "screenOff"
    """
    Event kind.
    """
    packageName: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app that produced the event.
    """


class UiEventScreenOn(BaseModel):
    """
    The screen turned on.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["screenOn"] = "screenOn"
    """
    Event kind.
    """
    packageName: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app that produced the event.
    """


class UiEventNode(BaseModel):
    """
    One visible accessibility node.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["image", "video", "web", "text", "list", "post", "other"]
    """
    Coarse node kind.
    """
    rect: Rect
    """
    Node bounds on screen.
    """
    nodeId: str | None = Field(None, max_length=128)
    """
    Node identifier.
    """
    text: str | None = Field(None, max_length=2000)
    """
    Node text.
    """
    contentDescription: str | None = Field(None, max_length=500)
    """
    Node content description.
    """
    className: str | None = Field(None, max_length=200)
    """
    Android class name.
    """


class Region(BaseModel):
    """
    A piece of the screen proposed by the Spotter for describing and judging. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    regionId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Unique within its look.
    """
    lookId: int = Field(..., ge=0)
    """
    The look (one run of find, describe, judge) this region belongs to.
    """
    frameId: int | None = Field(None, ge=0)
    """
    Frame the region was cut from.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the region was proposed.
    """
    rect: Rect
    """
    Region bounds on screen.
    """
    source: Literal["whole", "tile", "layout", "finder", "crop"]
    """
    How the region was proposed.
    """
    kind: Literal["screen", "post", "image", "video", "text", "object", "unknown"]
    """
    What the region contains.
    """
    objectness: float | None = Field(None, ge=0.0, le=1.0)
    """
    The finder's score.
    """
    postRect: Rect | None = None
    """
    Bounds of the enclosing post, for whole-post covers.
    """
    parentRegionId: str | None = Field(
        None, pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
    )
    """
    The region this one was cut from.
    """
    text: str | None = Field(None, max_length=2000)
    """
    Text of a text region.
    """
    phash: str | None = Field(None, pattern="^[0-9a-f]{16}$")
    """
    64-bit picture hash of the crop, used as the memory key.
    """
    ownOverlayFraction: float | None = Field(None, ge=0.0, le=1.0)
    """
    Share of the region hidden by Veil's own covers.
    """


class Embedding(BaseModel):
    """
    A fingerprint (meaning vector) of an image piece or a text prompt. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16. A fingerprint may only be compared with a concept from the same model family: both must carry the same spaceId.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    spaceId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Model family the fingerprint belongs to.
    """
    modelId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    The model that produced it; matches ModelManifest.modelId.
    """
    dim: int = Field(..., ge=1, le=4096)
    """
    Number of vector elements.
    """
    vectorF16: str = Field(..., min_length=4, pattern="^[A-Za-z0-9+/]*={0,2}$")
    """
    Standard base64 with padding of dim little-endian IEEE-754 binary16 values, L2-normalised. The byte length 2 x dim is checked by rules.py.
    """
    kind: Literal["image", "text", "region", "centroid"]
    """
    What was fingerprinted.
    """
    regionId: str | None = Field(None, pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Region the fingerprint was computed from.
    """
    text: str | None = Field(None, max_length=500)
    """
    The prompt, for text kind.
    """


class ConceptExamplePhoto(BaseModel):
    """
    One example photo that the user supplied for a concept.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    path: str = Field(..., max_length=260, min_length=1)
    """
    File path of the photo.
    """
    sha256: str = Field(..., pattern="^[0-9a-f]{64}$")
    """
    SHA-256 of the file.
    """


class LooksLikeItem(RootModel[str]):
    root: str = Field(..., max_length=200, min_length=1)


class ButNotItem(RootModel[str]):
    root: str = Field(..., max_length=200, min_length=1)


class IgnoreItem(RootModel[str]):
    root: str = Field(..., max_length=200, min_length=1)


class Keyword(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class AlsoHideItem(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class Concept(BaseModel):
    """
    The user-facing definition of one dislike: the concept card's words, lookalikes and settings. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    conceptId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Stable identifier of the concept.
    """
    displayName: str = Field(..., max_length=64, min_length=1)
    """
    Name shown to the user.
    """
    layer: Literal[1, 2]
    """
    1 is the always-on safety layer, 2 is the user's own list.
    """
    enabled: bool
    """
    Whether the concept is switched on.
    """
    looksLike: list[LooksLikeItem] = Field(..., max_length=32, min_length=1)
    """
    Words describing what to hide.
    """
    butNot: list[ButNotItem] = Field(..., max_length=32, min_length=0)
    """
    Lookalikes that must not be hidden.
    """
    ignore: list[IgnoreItem] | None = Field(None, max_length=16, min_length=0)
    """
    Things to ignore; when omitted the Teacher uses the shared ignore list.
    """
    keywords: list[Keyword] | None = Field(None, max_length=64, min_length=0)
    """
    Keyword rules for the text lane.
    """
    examplePhotos: list[ConceptExamplePhoto] | None = Field(
        None, max_length=16, min_length=0
    )
    """
    Example photos plus their checksums.
    """
    scope: Literal["object", "wholeElement"]
    """
    Cover only the object, or the whole element around it.
    """
    coverStyle: Literal["solid", "blur", "mosaic"]
    """
    How the cover looks. Layer 1 is always solid.
    """
    showLabel: bool
    """
    Whether the cover shows a label.
    """
    strictness: Literal["light", "balanced", "strict"] | None = None
    """
    A per-concept override; when omitted the global mode applies.
    """
    sensitive: bool | None = None
    """
    True for sensitive topics (hidden from previews).
    """
    alsoHide: list[AlsoHideItem] | None = Field(None, max_length=16)
    """
    Lookalike names the user chose to hide too (Chapter 7).
    """


class ConceptPackAccuracy(BaseModel):
    """
    Measured accuracy of a pack on a named test set.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    recall: float = Field(..., ge=0.0, le=1.0)
    """
    Share of target items that were covered.
    """
    cleanFalseCoverRate: float = Field(..., ge=0.0, le=1.0)
    """
    Share of clean items that were covered by mistake.
    """
    testImages: int = Field(..., ge=1)
    """
    Number of test images.
    """
    testSet: str = Field(..., max_length=100, min_length=1)
    """
    Name of the test set.
    """


class ConceptPack(BaseModel):
    """
    A named, versioned set of concepts (a topic pack). Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    packId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Stable identifier of the pack.
    """
    name: str = Field(..., max_length=80, min_length=1)
    """
    Pack name.
    """
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    Pack version (major.minor.patch).
    """
    description: str = Field(..., max_length=2000)
    """
    What the pack covers, including measured accuracy.
    """
    sensitive: bool
    """
    True for sensitive topics.
    """
    concepts: list[Concept] = Field(..., max_length=64, min_length=1)
    """
    The concepts in the pack.
    """
    accuracy: ConceptPackAccuracy | None = None
    """
    Measured accuracy of the pack.
    """
    licence: str | None = Field(None, max_length=64)
    """
    Licence of the pack.
    """


class CompiledConceptThresholds(BaseModel):
    """
    Decision thresholds per strictness mode.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    light: float = Field(..., ge=0.0, le=1.0)
    """
    Threshold in light mode.
    """
    balanced: float = Field(..., ge=0.0, le=1.0)
    """
    Threshold in balanced mode.
    """
    strict: float = Field(..., ge=0.0, le=1.0)
    """
    Threshold in strict mode.
    """


class CompiledConceptAutoThresholds3(BaseModel):
    """
    Cosine thresholds per mode.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    light: float = Field(..., ge=-1.0, le=1.0)
    """
    Threshold in light mode.
    """
    balanced: float = Field(..., ge=-1.0, le=1.0)
    """
    Threshold in balanced mode.
    """
    strict: float = Field(..., ge=-1.0, le=1.0)
    """
    Threshold in strict mode.
    """


class CompiledConceptAutoThresholds1(BaseModel):
    """
    Balanced cosine threshold.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    balanced: float = Field(..., ge=-1.0, le=1.0)
    """
    Threshold in balanced mode.
    """


class CompiledConceptAutoTerm(BaseModel):
    """
    A positive term of the auto rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    term: str = Field(..., max_length=64, min_length=1)
    """
    The word.
    """
    embedding: Embedding
    """
    Ensemble text fingerprint of the word.
    """
    thresholds: CompiledConceptAutoThresholds3
    """
    Null-quantile cosine thresholds.
    """


class CompiledConceptAutoCompetitor(BaseModel):
    """
    A competitor term of the auto rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    term: str = Field(..., max_length=64, min_length=1)
    """
    The word.
    """
    embedding: Embedding
    """
    Ensemble text fingerprint of the word.
    """
    thresholds: CompiledConceptAutoThresholds1
    """
    Null-quantile cosine thresholds.
    """


class Chip(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class CompiledConceptAuto(BaseModel):
    """
    Optional self-calibrating rule (Chapter 7). When present the Judge takes the auto path.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    rule: Literal["null-quantile-v1", "null-quantile-v2"]
    bankId: str = Field(..., max_length=64, min_length=1)
    """
    Id of the reference bank.
    """
    margin: float = Field(..., ge=-1.0, le=1.0)
    """
    Competitor margin.
    """
    excluded: int = Field(..., ge=0)
    """
    Bank rows excluded.
    """
    chips: list[Chip] = Field(..., max_length=16)
    """
    Lookalike names to offer.
    """
    positives: list[CompiledConceptAutoTerm] = Field(..., max_length=17, min_length=1)
    """
    Positive terms.
    """
    competitors: list[CompiledConceptAutoCompetitor] = Field(..., max_length=256)
    """
    Competitor terms.
    """


class CompiledConcept(BaseModel):
    """
    A concept compiled into fingerprints for one model family, ready for the Judge. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16. A fingerprint may only be compared with a concept from the same model family: both must carry the same spaceId.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    conceptId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    The concept this was compiled from.
    """
    spaceId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Model family of every fingerprint inside.
    """
    textModelId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    The text encoder that produced the text fingerprints.
    """
    conceptSha256: str = Field(..., pattern="^[0-9a-f]{64}$")
    """
    Hash of the canonical JSON of the source Concept (see rules.concept_sha256), so phone-built and Workshop-built cards can be compared.
    """
    looksLike: list[Embedding] = Field(..., max_length=32, min_length=1)
    """
    Fingerprints of the looksLike phrases.
    """
    butNot: list[Embedding] = Field(..., max_length=32, min_length=0)
    """
    Fingerprints of the butNot phrases.
    """
    ignore: list[Embedding] = Field(..., max_length=16, min_length=0)
    """
    Fingerprints of the ignore phrases.
    """
    exampleCentroid: Embedding | None = None
    """
    Centroid of the example photos' fingerprints.
    """
    exampleCount: int = Field(..., ge=0, le=16)
    """
    Number of example photos behind the centroid.
    """
    exceptions: list[Embedding] = Field(..., max_length=64)
    """
    "That's not it" fingerprints from user feedback.
    """
    calibrationOffset: float = Field(..., ge=-1.0, le=1.0)
    """
    Offset from calibration.
    """
    userOffset: float = Field(..., ge=-0.15, le=0.15)
    """
    Offset from the user's feedback, capped at 0.15 either way.
    """
    thresholds: CompiledConceptThresholds
    """
    Thresholds per strictness mode.
    """
    margin: float = Field(..., ge=0.0, le=1.0)
    """
    Judge margin.
    """
    exampleThreshold: float | None = Field(None, ge=0.0, le=1.0)
    """
    Threshold for matches against the example centroid.
    """
    auto: CompiledConceptAuto | None = None
    """
    Optional self-calibrating rule (Chapter 7). When present the Judge takes the auto path.
    """


class Finding(BaseModel):
    """
    The Judge's verdict on one piece for one concept, or a Layer 1 detector hit. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    findingId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Unique identifier of the finding.
    """
    lookId: int = Field(..., ge=0)
    """
    The look this finding belongs to.
    """
    tMs: int = Field(..., ge=0)
    """
    Time of the verdict.
    """
    frameId: int | None = Field(None, ge=0)
    """
    Frame the piece was cut from.
    """
    image: str | None = Field(None, max_length=260, min_length=1)
    """
    Screenshot file name in offline evaluation.
    """
    regionId: str | None = Field(None, pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    The region that was judged.
    """
    rect: Rect
    """
    Bounds of the finding on screen.
    """
    conceptId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    The concept judged; Layer 1 ids look like l1.nudity and l1.abuse.
    """
    layer: Literal[1, 2]
    """
    1 is the always-on safety layer, 2 is the user's own list.
    """
    lane: Literal["describer", "finder", "layer1", "text"]
    """
    Which lane produced the finding.
    """
    decision: Literal["hide", "nearMiss", "leave"]
    """
    hide is a confident finding; nearMiss is a near-threshold finding that only keeps existing covers alive; leave is no finding.
    """
    probability: float = Field(..., ge=0.0, le=1.0)
    """
    Probability that the piece matches the concept.
    """
    score: float | None = Field(None, ge=-1.0, le=1.0)
    """
    Raw similarity score.
    """
    margin: float | None = Field(None, ge=-2.0, le=2.0)
    """
    Margin over the best lookalike.
    """
    scope: Literal["object", "wholeElement"]
    """
    Cover only the object, or the whole element around it.
    """


class Track(BaseModel):
    """
    The Follower's state for one cover that follows an item across frames and scrolls. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    trackId: int = Field(..., ge=1)
    """
    Assigned in creation order (deterministic tie-breaking).
    """
    conceptId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    The concept being followed.
    """
    layer: Literal[1, 2]
    """
    1 is the always-on safety layer, 2 is the user's own list.
    """
    rect: Rect
    """
    Current position after scroll shifts.
    """
    state: Literal["tentative", "confirmed", "parked", "released"]
    """
    Lifecycle state of the track.
    """
    sightings: int = Field(..., ge=0)
    """
    Number of times the item was seen.
    """
    firstSeenMs: int = Field(..., ge=0)
    """
    Time of the first sighting.
    """
    lastSeenMs: int = Field(..., ge=0)
    """
    Time of the latest sighting.
    """
    holdUntilMs: int = Field(..., ge=0)
    """
    The cover is kept at least until this time.
    """
    maxHoldUntilMs: int = Field(..., ge=0)
    """
    The cover is never kept past this time.
    """
    parkedUntilMs: int | None = Field(None, ge=0)
    """
    When a parked track expires.
    """
    selfCaptureFraction: float = Field(..., ge=0.0, le=1.0)
    """
    Share of the item hidden by Veil's own covers.
    """
    peeked: bool
    """
    True while the user is peeking under the cover.
    """
    scope: Literal["object", "wholeElement"]
    """
    Cover only the object, or the whole element around it.
    """
    lastFindingId: str | None = Field(
        None, pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$"
    )
    """
    The finding that last confirmed the track.
    """


class ConceptId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")


class TrackId(RootModel[int]):
    root: int = Field(..., ge=1)


class Mask(BaseModel):
    """
    One cover to draw. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    maskId: int = Field(..., ge=1)
    """
    Identifier of the cover.
    """
    rect: Rect
    """
    Cover bounds on screen, already padded.
    """
    style: Literal["solid", "blur", "mosaic"]
    """
    How the cover looks.
    """
    layer: Literal[1, 2]
    """
    1 is the always-on safety layer, 2 is the user's own list.
    """
    peekable: bool
    """
    Whether the user may peek under the cover. Never true for Layer 1.
    """
    label: str | None = Field(None, max_length=64, min_length=1)
    """
    Text shown on the cover, e.g. Hidden · cats.
    """
    conceptIds: list[ConceptId] = Field(..., max_length=8, min_length=1)
    """
    Concepts that caused the cover.
    """
    trackIds: list[TrackId] = Field(..., max_length=32, min_length=1)
    """
    Tracks the cover follows.
    """


class MaskPlan(BaseModel):
    """
    The complete set of covers to draw now. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    planId: int = Field(..., ge=0)
    """
    Increases with every new plan.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the plan was made.
    """
    screenWidth: int = Field(..., ge=1, le=16384)
    """
    Screen width the rects refer to.
    """
    screenHeight: int = Field(..., ge=1, le=16384)
    """
    Screen height the rects refer to.
    """
    rotation: Literal[0, 90, 180, 270]
    """
    Display rotation in degrees.
    """
    masks: list[Mask] = Field(..., max_length=24)
    """
    The covers to draw (at most 24).
    """
    basedOnFrameId: int | None = Field(None, ge=0)
    """
    Frame the plan was computed from.
    """
    reason: Literal["look", "scroll", "expire", "peek", "clear", "appChange"]
    """
    Why a new plan was made.
    """


class Feedback(BaseModel):
    """
    A user correction on a Layer 2 cover. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16. A fingerprint may only be compared with a concept from the same model family: both must carry the same spaceId.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    feedbackId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Unique identifier of the feedback.
    """
    tMs: int = Field(..., ge=0)
    """
    Time of the correction.
    """
    kind: Literal["notThis", "missed", "correct"]
    """
    notThis: wrongly covered; missed: should have been covered; correct: confirmed.
    """
    conceptId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    The concept the correction is about.
    """
    layer: Literal[2] = 2
    """
    Always 2: Layer 1 cannot be corrected.
    """
    spaceId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Model family of the embedding.
    """
    embedding: Embedding | None = None
    """
    Fingerprint of the corrected piece.
    """
    rect: Rect | None = None
    """
    Bounds of the corrected piece on screen.
    """
    trackId: int | None = Field(None, ge=1)
    """
    The track that was corrected.
    """
    source: Literal["longPress", "recentCovers", "screenshot"]
    """
    Where the correction was made.
    """
    thumbnailPath: str | None = Field(None, max_length=260, min_length=1)
    """
    A phone-local thumbnail file only.
    """


class ShapeItem(RootModel[int]):
    root: int = Field(..., ge=1)


class ModelManifestTensorSpec(BaseModel):
    """
    One input or output tensor with a fixed shape.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., max_length=64, min_length=1)
    """
    Tensor name.
    """
    shape: list[ShapeItem] = Field(..., max_length=8, min_length=1)
    """
    Fixed shape; dynamic dimensions are not allowed.
    """
    dtype: Literal["float32", "float16", "uint8", "int8", "uint16", "int16", "int32", "int64", "bool"]
    """
    Element type.
    """


class ModelManifestPreprocessing(BaseModel):
    """
    How to prepare input for the model.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["image", "text", "none"]
    """
    Kind of input.
    """
    resizeWidth: int | None = Field(None, ge=1, le=4096)
    """
    Resize width.
    """
    resizeHeight: int | None = Field(None, ge=1, le=4096)
    """
    Resize height.
    """
    resizeMode: Literal["stretch", "letterbox", "centerCrop"] | None = None
    """
    How to resize.
    """
    colorOrder: Literal["RGB", "BGR"] | None = None
    """
    Channel order.
    """
    layout: Literal["NCHW", "NHWC"] | None = None
    """
    Tensor layout.
    """
    scale: float | None = None
    """
    Multiplier applied to pixel values.
    """
    mean: list[float] | None = Field(None, max_length=4, min_length=1)
    """
    Per-channel mean.
    """
    std: list[float] | None = Field(None, max_length=4, min_length=1)
    """
    Per-channel standard deviation.
    """
    tokenizer: str | None = Field(None, max_length=100)
    """
    Tokenizer name.
    """
    maxTokens: int | None = Field(None, ge=1, le=1024)
    """
    Maximum number of tokens.
    """


class ModelManifestFingerprint(BaseModel):
    """
    What a fingerprint model produces.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    spaceId: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Model family of the fingerprints.
    """
    dim: int = Field(..., ge=1, le=4096)
    """
    Number of vector elements.
    """
    role: Literal["image", "text", "region"]
    """
    What the model embeds.
    """
    pairedWith: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    The modelId of the paired encoder (for image and region models, their text encoder).
    """


class ModelManifestFile(BaseModel):
    """
    The model file.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    path: str = Field(..., max_length=260, min_length=1)
    """
    Path of the file.
    """
    sha256: str = Field(..., pattern="^[0-9a-f]{64}$")
    """
    SHA-256 of the file.
    """
    bytes: int = Field(..., ge=1)
    """
    Size in bytes.
    """


class ModelManifest(BaseModel):
    """
    Everything the phone needs to load and use one model file. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16. A fingerprint may only be compared with a concept from the same model family: both must carry the same spaceId.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    modelId: str = Field(..., pattern="^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$")
    """
    Stable identifier of the model.
    """
    name: str = Field(..., max_length=100, min_length=1)
    """
    Model name.
    """
    version: str = Field(..., max_length=40, min_length=1)
    """
    Model version.
    """
    task: Literal["imageEmbedding", "textEmbedding", "objectFinder", "nsfwDetector", "toxicityClassifier", "ocr", "other"]
    """
    What the model does.
    """
    inputs: list[ModelManifestTensorSpec] = Field(..., max_length=16, min_length=1)
    """
    Input tensors.
    """
    outputs: list[ModelManifestTensorSpec] = Field(..., max_length=16, min_length=1)
    """
    Output tensors.
    """
    preprocessing: ModelManifestPreprocessing
    """
    Input preparation.
    """
    fingerprint: ModelManifestFingerprint | None = None
    """
    Fingerprint details; required for embedding and finder tasks.
    """
    precision: Literal["float32", "float16", "w8a16", "w8a8", "w4a16"]
    """
    Numeric precision of the file.
    """
    runtime: Literal["onnxruntime-qnn", "onnxruntime-cpu", "litert-npu", "litert-cpu", "mlkit"]
    """
    Runtime to load it with.
    """
    batch: int = Field(..., ge=1, le=64)
    """
    Batch size.
    """
    file: ModelManifestFile
    """
    The model file.
    """
    sourceUrl: str = Field(..., pattern="^https://")
    """
    Where the model came from.
    """
    licence: str = Field(..., max_length=64, min_length=1)
    """
    Licence of the model.
    """
    notes: str | None = Field(None, max_length=2000)
    """
    Free-form notes.
    """


class EngineStats(BaseModel):
    """
    Periodic statistics published by the Guard. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the statistics were published.
    """
    windowMs: int = Field(..., ge=1, le=600000)
    """
    Length of the window the statistics cover.
    """
    mode: Literal["light", "balanced", "strict"]
    """
    Global strictness mode.
    """
    schedulerState: Literal["idle", "watching", "hot", "throttled"]
    """
    State of the Gatekeeper.
    """
    captureState: Literal["running", "paused", "stopped", "awaitingPermission"]
    """
    State of screen capture.
    """
    captureStopReason: str | None = Field(None, max_length=120)
    """
    Why capture stopped.
    """
    captureSource: Literal["mediaProjection", "accessibilityScreenshot", "replay"] | None = (
        None
    )
    """
    Capture source in use.
    """
    foregroundPackage: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app in the foreground.
    """
    looksPerSecond: float = Field(..., ge=0.0)
    """
    Looks per second in the window.
    """
    looksTotal: int = Field(..., ge=0)
    """
    Looks since start.
    """
    framesSeen: int = Field(..., ge=0)
    """
    Frames seen.
    """
    framesAnalysed: int = Field(..., ge=0)
    """
    Frames analysed.
    """
    framesSkipped: int = Field(..., ge=0)
    """
    Frames skipped.
    """
    cacheHits: int = Field(..., ge=0)
    """
    Memory cache hits.
    """
    cacheMisses: int = Field(..., ge=0)
    """
    Memory cache misses.
    """
    activeTracks: int = Field(..., ge=0)
    """
    Tracks being followed.
    """
    activeCovers: int = Field(..., ge=0, le=24)
    """
    Covers on screen (at most 24).
    """
    aiMsLastLook: float | None = Field(None, ge=0.0)
    """
    AI time of the last look.
    """
    lookMsP50: float | None = Field(None, ge=0.0)
    """
    Median look time.
    """
    lookMsP95: float | None = Field(None, ge=0.0)
    """
    95th percentile look time.
    """
    memoryPssKb: int | None = Field(None, ge=0)
    """
    Proportional set size in kilobytes.
    """
    thermalStatus: int | None = Field(None, ge=0, le=6)
    """
    Android PowerManager THERMAL_STATUS_* value.
    """
    batteryImpactPctPerHour: float | None = Field(None, ge=0.0)
    """
    Estimated battery impact in percent per hour.
    """


class ScreenLabelBox(BaseModel):
    """
    One labelled box.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    rect: Rect
    """
    Box bounds in screenshot pixels.
    """
    concept: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    The concept present in the box.
    """
    kind: Literal["photo", "cartoon", "drawing", "sticker", "emoji", "text", "other"]
    """
    How the content is depicted.
    """
    tag: str | None = Field(None, pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    Free tag such as cat-emoji or cat-text.
    """
    scope: Literal["object", "wholeElement"]
    """
    Cover only the object, or the whole element around it.
    """
    visibleFraction: float | None = Field(None, ge=0.0, le=1.0)
    """
    Share of the item that is visible.
    """
    postRect: Rect | None = None
    """
    Bounds of the enclosing post.
    """


class ScreenLabelMeta(BaseModel):
    """
    Where the screenshot came from.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    app: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")
    """
    App the screenshot was taken in.
    """
    surface: str = Field(..., max_length=40, min_length=1)
    """
    Part of the app, e.g. explore-grid.
    """
    mode: Literal["dark", "light"]
    """
    Colour mode.
    """
    orientation: Literal["portrait", "landscape"]
    """
    Screen orientation.
    """
    source: str = Field(..., max_length=40, min_length=1)
    """
    How the screenshot was captured.
    """


class Lookalike(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9][a-z0-9._-]{0,63}$")


class ScreenLabel(BaseModel):
    """
    Ground-truth labels for one screenshot (the Phase 1.2 label format). Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    image: str = Field(..., pattern="^[A-Za-z0-9._-]+\\.png$")
    """
    Screenshot file name.
    """
    width: int = Field(..., ge=1, le=16384)
    """
    Screenshot width in pixels.
    """
    height: int = Field(..., ge=1, le=16384)
    """
    Screenshot height in pixels.
    """
    clean: bool
    """
    True means no labelled concept is present.
    """
    boxes: list[ScreenLabelBox] = Field(..., max_length=200)
    """
    Labelled boxes.
    """
    lookalikes: list[Lookalike] | None = Field(None, max_length=16)
    """
    Lookalike content present, e.g. dog or fox.
    """
    meta: ScreenLabelMeta | None = None
    """
    Where the screenshot came from.
    """
    labeller: str | None = Field(None, max_length=40)
    """
    Who labelled the screenshot.
    """
    reviewed: bool | None = None
    """
    True once a second person reviewed the labels.
    """


class UiEventNodesSnapshot(BaseModel):
    """
    A snapshot of the visible accessibility nodes.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal["1.0"] = "1.0"
    """
    Contract version this object follows.
    """
    eventId: int = Field(..., ge=0)
    """
    Per-session event sequence number.
    """
    tMs: int = Field(..., ge=0)
    """
    Time the event happened.
    """
    type: Literal["nodesSnapshot"] = "nodesSnapshot"
    """
    Event kind.
    """
    packageName: str | None = Field(
        None, pattern="^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$"
    )
    """
    Package name of the app that produced the event.
    """
    nodes: list[UiEventNode] = Field(..., max_length=300)
    """
    Visible nodes (at most 300).
    """
    truncated: bool
    """
    True if the node limit or the time budget was hit.
    """
    durationMs: int = Field(..., ge=0)
    """
    Time the snapshot took.
    """


class UiEvent(
    RootModel[
        UiEventScrolled
        | UiEventWindowChanged
        | UiEventContentChanged
        | UiEventNodesSnapshot
        | UiEventScreenOff
        | UiEventScreenOn
    ]
):
    root: (
        UiEventScrolled
        | UiEventWindowChanged
        | UiEventContentChanged
        | UiEventNodesSnapshot
        | UiEventScreenOff
        | UiEventScreenOn
    ) = Field(..., title="UiEvent")
    """
    One screen signal from the accessibility service: scrolled, window changed, content changed, nodes snapshot, screen off or screen on. Veil contract v1.0. Units: positions and sizes are integer screen pixels with the origin at the top-left of the display in its current orientation (x grows right, y grows down); times are integer milliseconds on one monotonic clock (Android SystemClock.uptimeMillis; replays use a virtual clock in the same unit); fingerprints are L2-normalised vectors stored as float16.
    """
