// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.veil.console.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object GuardApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class HelloMsg (
  val protocolVersion: Long,
  val contractVersion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HelloMsg {
      val protocolVersion = pigeonVar_list[0] as Long
      val contractVersion = pigeonVar_list[1] as String
      return HelloMsg(protocolVersion, contractVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      protocolVersion,
      contractVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HelloMsg
    return GuardApiPigeonUtils.deepEquals(this.protocolVersion, other.protocolVersion) && GuardApiPigeonUtils.deepEquals(this.contractVersion, other.contractVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.protocolVersion)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.contractVersion)
    return result
  }
  override fun toString(): String {
    return "HelloMsg(protocolVersion=$protocolVersion, contractVersion=$contractVersion)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FileRefMsg (
  val path: String,
  val sha256: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FileRefMsg {
      val path = pigeonVar_list[0] as String
      val sha256 = pigeonVar_list[1] as String
      return FileRefMsg(path, sha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      sha256,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FileRefMsg
    return GuardApiPigeonUtils.deepEquals(this.path, other.path) && GuardApiPigeonUtils.deepEquals(this.sha256, other.sha256)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.path)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.sha256)
    return result
  }
  override fun toString(): String {
    return "FileRefMsg(path=$path, sha256=$sha256)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConceptMsg (
  val conceptId: String,
  val displayName: String,
  val enabled: Boolean,
  val looksLike: List<String>,
  val butNot: List<String>,
  val coverStyle: String,
  val examplePhotos: List<FileRefMsg>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConceptMsg {
      val conceptId = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val enabled = pigeonVar_list[2] as Boolean
      val looksLike = pigeonVar_list[3] as List<String>
      val butNot = pigeonVar_list[4] as List<String>
      val coverStyle = pigeonVar_list[5] as String
      val examplePhotos = pigeonVar_list[6] as List<FileRefMsg>
      return ConceptMsg(conceptId, displayName, enabled, looksLike, butNot, coverStyle, examplePhotos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conceptId,
      displayName,
      enabled,
      looksLike,
      butNot,
      coverStyle,
      examplePhotos,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConceptMsg
    return GuardApiPigeonUtils.deepEquals(this.conceptId, other.conceptId) && GuardApiPigeonUtils.deepEquals(this.displayName, other.displayName) && GuardApiPigeonUtils.deepEquals(this.enabled, other.enabled) && GuardApiPigeonUtils.deepEquals(this.looksLike, other.looksLike) && GuardApiPigeonUtils.deepEquals(this.butNot, other.butNot) && GuardApiPigeonUtils.deepEquals(this.coverStyle, other.coverStyle) && GuardApiPigeonUtils.deepEquals(this.examplePhotos, other.examplePhotos)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.conceptId)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.looksLike)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.butNot)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.coverStyle)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.examplePhotos)
    return result
  }
  override fun toString(): String {
    return "ConceptMsg(conceptId=$conceptId, displayName=$displayName, enabled=$enabled, looksLike=$looksLike, butNot=$butNot, coverStyle=$coverStyle, examplePhotos=$examplePhotos)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StateMsg (
  val protocolVersion: Long,
  val running: Boolean,
  val mode: String,
  val captureState: String,
  val permissions: Map<String, Boolean>,
  val skipList: List<String>,
  val concepts: List<ConceptMsg>,
  val activePackSha256: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StateMsg {
      val protocolVersion = pigeonVar_list[0] as Long
      val running = pigeonVar_list[1] as Boolean
      val mode = pigeonVar_list[2] as String
      val captureState = pigeonVar_list[3] as String
      val permissions = pigeonVar_list[4] as Map<String, Boolean>
      val skipList = pigeonVar_list[5] as List<String>
      val concepts = pigeonVar_list[6] as List<ConceptMsg>
      val activePackSha256 = pigeonVar_list[7] as String?
      return StateMsg(protocolVersion, running, mode, captureState, permissions, skipList, concepts, activePackSha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      protocolVersion,
      running,
      mode,
      captureState,
      permissions,
      skipList,
      concepts,
      activePackSha256,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StateMsg
    return GuardApiPigeonUtils.deepEquals(this.protocolVersion, other.protocolVersion) && GuardApiPigeonUtils.deepEquals(this.running, other.running) && GuardApiPigeonUtils.deepEquals(this.mode, other.mode) && GuardApiPigeonUtils.deepEquals(this.captureState, other.captureState) && GuardApiPigeonUtils.deepEquals(this.permissions, other.permissions) && GuardApiPigeonUtils.deepEquals(this.skipList, other.skipList) && GuardApiPigeonUtils.deepEquals(this.concepts, other.concepts) && GuardApiPigeonUtils.deepEquals(this.activePackSha256, other.activePackSha256)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.protocolVersion)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.running)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.mode)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.captureState)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.permissions)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.skipList)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.concepts)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.activePackSha256)
    return result
  }
  override fun toString(): String {
    return "StateMsg(protocolVersion=$protocolVersion, running=$running, mode=$mode, captureState=$captureState, permissions=$permissions, skipList=$skipList, concepts=$concepts, activePackSha256=$activePackSha256)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StatsMsg (
  val tMs: Long,
  val looksPerSecond: Double,
  val aiMsLastLook: Double,
  val batteryImpactPctPerHour: Double,
  val activeCovers: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatsMsg {
      val tMs = pigeonVar_list[0] as Long
      val looksPerSecond = pigeonVar_list[1] as Double
      val aiMsLastLook = pigeonVar_list[2] as Double
      val batteryImpactPctPerHour = pigeonVar_list[3] as Double
      val activeCovers = pigeonVar_list[4] as Long
      return StatsMsg(tMs, looksPerSecond, aiMsLastLook, batteryImpactPctPerHour, activeCovers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      tMs,
      looksPerSecond,
      aiMsLastLook,
      batteryImpactPctPerHour,
      activeCovers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatsMsg
    return GuardApiPigeonUtils.deepEquals(this.tMs, other.tMs) && GuardApiPigeonUtils.deepEquals(this.looksPerSecond, other.looksPerSecond) && GuardApiPigeonUtils.deepEquals(this.aiMsLastLook, other.aiMsLastLook) && GuardApiPigeonUtils.deepEquals(this.batteryImpactPctPerHour, other.batteryImpactPctPerHour) && GuardApiPigeonUtils.deepEquals(this.activeCovers, other.activeCovers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.tMs)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.looksPerSecond)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.aiMsLastLook)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.batteryImpactPctPerHour)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.activeCovers)
    return result
  }
  override fun toString(): String {
    return "StatsMsg(tMs=$tMs, looksPerSecond=$looksPerSecond, aiMsLastLook=$aiMsLastLook, batteryImpactPctPerHour=$batteryImpactPctPerHour, activeCovers=$activeCovers)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledAppMsg (
  val packageName: String,
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledAppMsg {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      return InstalledAppMsg(packageName, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InstalledAppMsg
    return GuardApiPigeonUtils.deepEquals(this.packageName, other.packageName) && GuardApiPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.label)
    return result
  }
  override fun toString(): String {
    return "InstalledAppMsg(packageName=$packageName, label=$label)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecentCoverMsg (
  val coverId: String,
  val conceptId: String,
  val thumbnailPath: String,
  val tMs: Long,
  val mark: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecentCoverMsg {
      val coverId = pigeonVar_list[0] as String
      val conceptId = pigeonVar_list[1] as String
      val thumbnailPath = pigeonVar_list[2] as String
      val tMs = pigeonVar_list[3] as Long
      val mark = pigeonVar_list[4] as String?
      return RecentCoverMsg(coverId, conceptId, thumbnailPath, tMs, mark)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      coverId,
      conceptId,
      thumbnailPath,
      tMs,
      mark,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecentCoverMsg
    return GuardApiPigeonUtils.deepEquals(this.coverId, other.coverId) && GuardApiPigeonUtils.deepEquals(this.conceptId, other.conceptId) && GuardApiPigeonUtils.deepEquals(this.thumbnailPath, other.thumbnailPath) && GuardApiPigeonUtils.deepEquals(this.tMs, other.tMs) && GuardApiPigeonUtils.deepEquals(this.mark, other.mark)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.coverId)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.conceptId)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.thumbnailPath)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.tMs)
    result = 31 * result + GuardApiPigeonUtils.deepHash(this.mark)
    return result
  }
  override fun toString(): String {
    return "RecentCoverMsg(coverId=$coverId, conceptId=$conceptId, thumbnailPath=$thumbnailPath, tMs=$tMs, mark=$mark)"
  }
}
private open class GuardApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HelloMsg.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FileRefMsg.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConceptMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StateMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatsMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledAppMsg.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecentCoverMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HelloMsg -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is FileRefMsg -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ConceptMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is StateMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is StatsMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is InstalledAppMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RecentCoverMsg -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val GuardApiPigeonMethodCodec = StandardMethodCodec(GuardApiPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GuardHostApi {
  fun hello(): HelloMsg
  fun getState(): StateMsg
  fun start()
  fun stop()
  fun setMode(mode: String)
  fun setSkipList(packages: List<String>)
  fun installedApps(): List<InstalledAppMsg>
  fun compilePack(text: String, photos: List<FileRefMsg>): ConceptMsg
  fun setConceptPack(pack: FileRefMsg): String
  fun submitFeedback(coverId: String, kind: String)
  fun recentCovers(limit: Long): List<RecentCoverMsg>
  fun requestPermission(perm: String)

  companion object {
    /** The codec used by GuardHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      GuardApiPigeonCodec()
    }
    /** Sets up an instance of `GuardHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GuardHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.hello$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hello())
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.getState$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getState())
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.start$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.start()
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.stop$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.setMode$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.setSkipList$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packagesArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.setSkipList(packagesArg)
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.installedApps$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.installedApps())
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.compilePack$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val photosArg = args[1] as List<FileRefMsg>
            val wrapped: List<Any?> = try {
              listOf(api.compilePack(textArg, photosArg))
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.setConceptPack$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packArg = args[0] as FileRefMsg
            val wrapped: List<Any?> = try {
              listOf(api.setConceptPack(packArg))
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.submitFeedback$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val coverIdArg = args[0] as String
            val kindArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.submitFeedback(coverIdArg, kindArg)
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.recentCovers$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val limitArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.recentCovers(limitArg))
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.veil_console.GuardHostApi.requestPermission$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.requestPermission(permArg)
              listOf(null)
            } catch (exception: Throwable) {
              GuardApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class GuardApiPigeonStreamHandler<T>(
    val wrapper: GuardApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface GuardApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class StreamStateStreamHandler : GuardApiPigeonEventChannelWrapper<StateMsg> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.veil_console.GuardEvents.streamState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = GuardApiPigeonStreamHandler<StateMsg>(streamHandler)
      EventChannel(messenger, channelName, GuardApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from GuardApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<StateMsg>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class StreamStatsStreamHandler : GuardApiPigeonEventChannelWrapper<StatsMsg> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamStatsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.veil_console.GuardEvents.streamStats"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = GuardApiPigeonStreamHandler<StatsMsg>(streamHandler)
      EventChannel(messenger, channelName, GuardApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from GuardApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<StatsMsg>) {}

override fun onCancel(p0: Any?) {}
}
      
