"""Deterministic synthetic app screens (CC0, generated by Veil). No animals or objects."""

from __future__ import annotations

import random

from PIL import Image, ImageDraw, ImageFont

LICENCE = "CC0-1.0 (generated by Veil)"
W, H = 360, 720
WORDS = ["Home", "Search", "Settings", "Profile", "Messages", "Today", "Inbox", "Total", "Next"]


def _rgb(rng: random.Random, lo: int, hi: int) -> tuple[int, int, int]:
    return (rng.randint(lo, hi), rng.randint(lo, hi), rng.randint(lo, hi))


def render_screen(index: int) -> Image.Image:
    rng = random.Random(index)
    im = Image.new("RGB", (W, H), _rgb(rng, 200, 255))
    d = ImageDraw.Draw(im)
    font = ImageFont.load_default()
    bar = _rgb(rng, 0, 120)
    d.rectangle([0, 0, W, 56], fill=bar)
    d.text((16, 22), rng.choice(WORDS), fill=(255, 255, 255), font=font)
    y = 72
    while y < H - 120:
        kind = rng.choice(["avatar", "text", "button"])
        if kind == "avatar":
            d.rectangle([16, y, 64, y + 48], fill=_rgb(rng, 60, 200))
            for k in range(2):
                line = " ".join(rng.choices(WORDS, k=3))
                d.text((76, y + 8 + 18 * k), line, fill=(20, 20, 20), font=font)
            y += 64
        elif kind == "text":
            for _ in range(rng.randint(2, 5)):
                line = " ".join(rng.choices(WORDS, k=rng.randint(3, 6)))
                d.text((16, y), line, fill=(30, 30, 30), font=font)
                y += 16
            y += 12
        else:
            d.rectangle([16, y, W - 16, y + 40], fill=_rgb(rng, 30, 200))
            d.text((28, y + 14), rng.choice(WORDS), fill=(255, 255, 255), font=font)
            y += 56
    d.rectangle([0, H - 56, W, H], fill=bar)
    return im
